2018-02-22 03:37:39,287 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:37:39,288 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:37:44,879 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:37:44,879 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:37:50,467 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:37:50,467 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:37:56,806 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:37:56,806 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:38:02,397 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:38:02,397 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:38:09,240 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:38:09,240 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:38:16,191 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:38:16,192 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:38:24,720 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:38:24,721 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:38:33,876 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:38:33,876 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:38:45,563 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:38:45,564 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:39:29,753 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:39:29,753 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:39:33,796 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:39:33,796 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:39:34,839 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:39:34,839 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:39:38,883 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:39:38,883 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:39:40,427 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:39:40,428 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:39:44,470 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:39:44,471 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:39:46,769 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:39:50,814 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:39:50,815 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:39:51,858 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:39:52,384 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:39:52,385 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:39:56,403 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:39:56,403 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:39:57,947 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:39:57,948 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:40:03,242 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:40:03,242 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:40:05,537 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:40:05,538 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:40:08,958 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:40:08,959 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:40:12,382 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:40:12,382 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:40:17,493 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:40:17,493 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:40:22,603 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:40:22,604 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:40:30,246 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:40:30,247 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:40:37,887 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:40:37,888 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:40:49,332 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:40:49,332 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:40:53,375 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:40:53,375 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:41:10,509 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:41:10,509 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:41:14,553 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:41:14,554 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:41:27,813 - telegram.ext.updater - WARNING - Exiting immediately!
2018-02-22 03:41:40,249 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:41:40,249 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:41:44,293 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2018-02-22 03:41:44,294 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2018-02-22 03:42:16,533 - telegram.ext.updater - WARNING - Exiting immediately!
2018-02-22 03:44:22,005 - telegram.ext.updater - WARNING - Exiting immediately!
2018-02-22 03:45:06,418 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <telegram.ext.dispatcher.Dispatcher object at 0x7fca9c5da128>
2018-02-22 03:45:06,419 - JobQueue - DEBUG - JobQueue thread started
2018-02-22 03:45:06,420 - telegram.ext.updater - DEBUG - dispatcher - started
2018-02-22 03:45:06,420 - telegram.ext.updater - DEBUG - updater - started
2018-02-22 03:45:06,420 - telegram.ext.updater - DEBUG - Updater thread started
2018-02-22 03:45:06,421 - telegram.bot - DEBUG - Entering: set_webhook
2018-02-22 03:45:06,421 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.telegram.org
2018-02-22 03:45:06,427 - telegram.ext.dispatcher - DEBUG - Dispatcher started
2018-02-22 03:45:06,607 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot511422853:AAFd4NQXPKgKJafMMmgrrjq1eA3biIjOGw4/setWebhook HTTP/1.1" 200 68
2018-02-22 03:45:06,608 - telegram.bot - DEBUG - True
2018-02-22 03:45:06,608 - telegram.bot - DEBUG - Exiting: set_webhook
2018-02-22 03:45:06,608 - telegram.bot - DEBUG - Entering: get_updates
2018-02-22 03:45:17,236 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot511422853:AAFd4NQXPKgKJafMMmgrrjq1eA3biIjOGw4/getUpdates HTTP/1.1" 200 23
2018-02-22 03:45:17,237 - telegram.bot - DEBUG - No new updates found.
2018-02-22 03:45:17,237 - telegram.bot - DEBUG - []
2018-02-22 03:45:17,237 - telegram.bot - DEBUG - Exiting: get_updates
2018-02-22 03:45:17,237 - telegram.bot - DEBUG - Entering: get_updates
2018-02-22 03:45:17,399 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot511422853:AAFd4NQXPKgKJafMMmgrrjq1eA3biIjOGw4/getUpdates HTTP/1.1" 200 450
2018-02-22 03:45:17,401 - telegram.bot - DEBUG - Getting updates: [20330348]
2018-02-22 03:45:17,401 - telegram.bot - DEBUG - [<telegram.update.Update object at 0x7fca9c5ea7f0>]
2018-02-22 03:45:17,402 - telegram.bot - DEBUG - Exiting: get_updates
2018-02-22 03:45:17,402 - telegram.ext.dispatcher - DEBUG - Processing Update: {'message': {'group_chat_created': False, 'from': {'id': 323687805, 'first_name': 'Alexey', 'is_bot': False, 'last_name': 'Shilo', 'username': 'Alexpricker', 'language_code': 'ru-RU'}, 'caption_entities': [], 'supergroup_chat_created': False, 'message_id': 991, 'photo': [], 'new_chat_member': None, 'text': 'Найти задолженность', 'channel_chat_created': False, 'new_chat_members': [], 'date': 1519260316, 'chat': {'type': 'private', 'first_name': 'Alexey', 'username': 'Alexpricker', 'last_name': 'Shilo', 'id': 323687805}, 'delete_chat_photo': False, 'new_chat_photo': [], 'entities': []}, 'update_id': 20330348}
2018-02-22 03:45:17,402 - telegram.bot - DEBUG - Entering: get_updates
2018-02-22 03:45:17,403 - telegram.ext.conversationhandler - DEBUG - selecting conversation (323687805, 323687805) with state None
2018-02-22 03:45:27,453 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot511422853:AAFd4NQXPKgKJafMMmgrrjq1eA3biIjOGw4/getUpdates HTTP/1.1" 200 23
2018-02-22 03:45:27,454 - telegram.bot - DEBUG - No new updates found.
2018-02-22 03:45:27,454 - telegram.bot - DEBUG - []
2018-02-22 03:45:27,454 - telegram.bot - DEBUG - Exiting: get_updates
2018-02-22 03:45:27,455 - telegram.bot - DEBUG - Entering: get_updates
2018-02-22 03:45:37,497 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot511422853:AAFd4NQXPKgKJafMMmgrrjq1eA3biIjOGw4/getUpdates HTTP/1.1" 200 23
2018-02-22 03:45:37,498 - telegram.bot - DEBUG - No new updates found.
2018-02-22 03:45:37,498 - telegram.bot - DEBUG - []
2018-02-22 03:45:37,498 - telegram.bot - DEBUG - Exiting: get_updates
2018-02-22 03:45:37,498 - telegram.bot - DEBUG - Entering: get_updates
2018-02-22 03:45:47,541 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot511422853:AAFd4NQXPKgKJafMMmgrrjq1eA3biIjOGw4/getUpdates HTTP/1.1" 200 23
2018-02-22 03:45:47,542 - telegram.bot - DEBUG - No new updates found.
2018-02-22 03:45:47,542 - telegram.bot - DEBUG - []
2018-02-22 03:45:47,542 - telegram.bot - DEBUG - Exiting: get_updates
2018-02-22 03:45:47,542 - telegram.bot - DEBUG - Entering: get_updates
2018-02-22 03:45:57,586 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot511422853:AAFd4NQXPKgKJafMMmgrrjq1eA3biIjOGw4/getUpdates HTTP/1.1" 200 23
2018-02-22 03:45:57,587 - telegram.bot - DEBUG - No new updates found.
2018-02-22 03:45:57,588 - telegram.bot - DEBUG - []
2018-02-22 03:45:57,588 - telegram.bot - DEBUG - Exiting: get_updates
2018-02-22 03:45:57,588 - telegram.bot - DEBUG - Entering: get_updates
2018-02-22 03:46:07,631 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot511422853:AAFd4NQXPKgKJafMMmgrrjq1eA3biIjOGw4/getUpdates HTTP/1.1" 200 23
2018-02-22 03:46:07,632 - telegram.bot - DEBUG - No new updates found.
2018-02-22 03:46:07,632 - telegram.bot - DEBUG - []
2018-02-22 03:46:07,633 - telegram.bot - DEBUG - Exiting: get_updates
2018-02-22 03:46:07,633 - telegram.bot - DEBUG - Entering: get_updates
2018-02-22 03:46:17,676 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot511422853:AAFd4NQXPKgKJafMMmgrrjq1eA3biIjOGw4/getUpdates HTTP/1.1" 200 23
2018-02-22 03:46:17,677 - telegram.bot - DEBUG - No new updates found.
2018-02-22 03:46:17,678 - telegram.bot - DEBUG - []
2018-02-22 03:46:17,678 - telegram.bot - DEBUG - Exiting: get_updates
2018-02-22 03:46:17,678 - telegram.bot - DEBUG - Entering: get_updates
2018-02-22 03:46:27,720 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot511422853:AAFd4NQXPKgKJafMMmgrrjq1eA3biIjOGw4/getUpdates HTTP/1.1" 200 23
2018-02-22 03:46:27,721 - telegram.bot - DEBUG - No new updates found.
2018-02-22 03:46:27,721 - telegram.bot - DEBUG - []
2018-02-22 03:46:27,721 - telegram.bot - DEBUG - Exiting: get_updates
2018-02-22 03:46:27,722 - telegram.bot - DEBUG - Entering: get_updates
2018-02-22 03:46:37,950 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot511422853:AAFd4NQXPKgKJafMMmgrrjq1eA3biIjOGw4/getUpdates HTTP/1.1" 200 23
2018-02-22 03:46:37,951 - telegram.bot - DEBUG - No new updates found.
2018-02-22 03:46:37,951 - telegram.bot - DEBUG - []
2018-02-22 03:46:37,951 - telegram.bot - DEBUG - Exiting: get_updates
2018-02-22 03:46:37,952 - telegram.bot - DEBUG - Entering: get_updates
2018-02-22 03:46:49,685 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot511422853:AAFd4NQXPKgKJafMMmgrrjq1eA3biIjOGw4/getUpdates HTTP/1.1" 200 23
2018-02-22 03:46:49,686 - telegram.bot - DEBUG - No new updates found.
2018-02-22 03:46:49,686 - telegram.bot - DEBUG - []
2018-02-22 03:46:49,686 - telegram.bot - DEBUG - Exiting: get_updates
2018-02-22 03:46:49,687 - telegram.bot - DEBUG - Entering: get_updates
2018-02-22 03:46:59,888 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot511422853:AAFd4NQXPKgKJafMMmgrrjq1eA3biIjOGw4/getUpdates HTTP/1.1" 200 23
2018-02-22 03:46:59,890 - telegram.bot - DEBUG - No new updates found.
2018-02-22 03:46:59,890 - telegram.bot - DEBUG - []
2018-02-22 03:46:59,890 - telegram.bot - DEBUG - Exiting: get_updates
2018-02-22 03:46:59,890 - telegram.bot - DEBUG - Entering: get_updates
2018-02-22 03:47:09,933 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot511422853:AAFd4NQXPKgKJafMMmgrrjq1eA3biIjOGw4/getUpdates HTTP/1.1" 200 23
2018-02-22 03:47:09,934 - telegram.bot - DEBUG - No new updates found.
2018-02-22 03:47:09,934 - telegram.bot - DEBUG - []
2018-02-22 03:47:09,934 - telegram.bot - DEBUG - Exiting: get_updates
2018-02-22 03:47:09,935 - telegram.bot - DEBUG - Entering: get_updates
2018-02-22 03:47:19,979 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot511422853:AAFd4NQXPKgKJafMMmgrrjq1eA3biIjOGw4/getUpdates HTTP/1.1" 200 23
2018-02-22 03:47:19,980 - telegram.bot - DEBUG - No new updates found.
2018-02-22 03:47:19,980 - telegram.bot - DEBUG - []
2018-02-22 03:47:19,980 - telegram.bot - DEBUG - Exiting: get_updates
2018-02-22 03:47:19,980 - telegram.bot - DEBUG - Entering: get_updates
2018-02-22 03:47:30,022 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot511422853:AAFd4NQXPKgKJafMMmgrrjq1eA3biIjOGw4/getUpdates HTTP/1.1" 200 23
2018-02-22 03:47:30,023 - telegram.bot - DEBUG - No new updates found.
2018-02-22 03:47:30,024 - telegram.bot - DEBUG - []
2018-02-22 03:47:30,024 - telegram.bot - DEBUG - Exiting: get_updates
2018-02-22 03:47:30,024 - telegram.bot - DEBUG - Entering: get_updates
2018-02-22 03:47:40,067 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot511422853:AAFd4NQXPKgKJafMMmgrrjq1eA3biIjOGw4/getUpdates HTTP/1.1" 200 23
2018-02-22 03:47:40,069 - telegram.bot - DEBUG - No new updates found.
2018-02-22 03:47:40,069 - telegram.bot - DEBUG - []
2018-02-22 03:47:40,069 - telegram.bot - DEBUG - Exiting: get_updates
2018-02-22 03:47:40,069 - telegram.bot - DEBUG - Entering: get_updates
